# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da33326722d5b7d98ba732750724416fcb2d3abf58f9eda23268f8f4b3e2cdb45cba94a0c5c1b3cfd74a6d0229f931b9e772ae13c4c82cb97a5c2a3641635796

test:
  secret_key_base: c37f97bbe17c05ddafd0e90a56c9a9fd3da7bbea66f496c0fc84ba3d9a06913d941337c01d259445e1839a9db3b8fbe3a20b24d63f0d8cbb06c8d994321bbdd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
